repos:
  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
  -
    repo: "https://github.com/psf/black"
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7
  -
    repo: "https://gitlab.com/pycqa/flake8"
    rev: 3.7.7
    hooks:
      - id: flake8
